spring:
  profiles:
    active: dev
  application:
    name: walletapi

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/walletapi
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

pagination:
  items_per_page: 10